### ISSUE TITLE
[Enhancement] Prevent from hot updating and using root user to run on Linux

### ISSUE THREAD

**Issue by WhiredPlanck** [ohzff/Zff#2]
主题：避免在 Linux 上使用热更新与 root 身份运行

```
else if (strcmp(argv[1], "update") == 0)
  {
    system ("cd /usr/share/ohzff-zff && git pull && g++ zff_main_en.cpp -o /usr/bin/zff");
    return 0;
  }
```
Note: Prevent using hot update on ANY Linux platform.

And I noticed that this game using root to run, please DON'T DO that. This may lead to some security problems.

Cheers.

**Comment by langonginc** [comment]
- root运行

并不需要使用root运行游戏，用root运行游戏会导致配置文件变成root权限。

- 热更新

热更新的确会造成问题，但是我并没想用它来强制更新。这个热更新是因为我一个同学不是Ar**-Jas**，他不更新游戏，就说我里面有一堆bug（当时），包括机器人太弱，我基本都改了，然后他以懒得更新为理由，继续跟我报告问题，然后我就学习 Micro**** 搞得热更新。

**Comment by langonginc** [comment]
热更新会删掉的

**Comment by WhiredPlanck** [comment]
>     * root运行
> 
> 
> 并不需要使用root运行游戏，用root运行游戏会导致配置文件变成root权限。
> 
>     * 热更新
> 
> 
> 热更新的确会造成问题，但是我并没想用它来强制更新。这个热更新是因为我一个同学不是Ar**-Jas**，他不更新游戏，就说我里面有一堆bug（当时），包括机器人太弱，我基本都改了，然后他以懒得更新为理由，继续跟我报告问题，然后我就学习 Micro**** 搞得热更新。

我明白了，谢谢回复。root 的相关事宜我也没弄清楚，贸然脱口而出。

**Comment by langonginc** [comment]
热更新已经删了哈
